apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
         app: frontend
    spec:
      containers:
      - name: frontend
        image: abdennebi/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PRODUCT_URL
          value: "http://product"
        - name: STOCK_URL
          value: "http://stock"
        - name: PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10 # default is 10s
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 20
