apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: PRODUCT_URL
          value: http://product
        - name: STOCK_URL
          value: http://stock
        - name: PORT
          value: "80"
        image: gcr.io/cloudnativestack-playground/frontend:5ca63f0194641097c59e4a41acdfb62c5ba61ff9
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        name: frontend
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 20
