apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "80"
        image: gcr.io/cloudnativestack-playground/product-service:d7fc6443ef4e14eea7aa34ce84f53e8bab842455
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        name: product
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 20
