apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        image: gcr.io/cloudnativestack-playground/stock-service:7488b4988f026c7828c35c21f10a5485dbbea8cd
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        name: stock
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 20
